### ISSUE TITLE
Mi5 hebrew sms letters turn into white spaces

### ISSUE THREAD

**Issue by bakinat** [ingbrzy/MIUI-XML-V8-HEBREW#4]
I see the problem in latest xiaomi.eu updates, including the latest (7.3.30). All hebrew letters turn blank when i send them from my mi5. The receptient just gets white spaces in the message. Thanks. Barak

**Comment by IgorEisberg** [comment]
Don't even know how that might be related with the translation, it sounds like a functionality bug.
Anyway, the Hebrew translation isn't maintained by me anymore, I even think that Hebrew should be removed from the European ROM altogether.

**Comment by ingbrzy** [comment]
disable "Use GSM Alphabet" in the SMS app settings...

**Comment by bakinat** [comment]
Thanks! It wasn’t enabled, but I enabled and disabled it and it works!

Sorry for not understanding that the git project is only for UI translation..

(Why do you think it should be moved out of xiaomi.eu? Is there an alternative project?

**Comment by IgorEisberg** [comment]
Because the Israeli Xiaomi community is about the most lowlife bunch I've ever encountered in my developer history, and I don't think they deserve a ROM such as this.
They are so clueless that they shouldn't even be tinkering with custom ROMs at all, they should stick to the global ROM. People like you don't necessarily need Hebrew interface, as you clearly read/write in English fluently.

And another reason is simply because there doesn't seem to be anyone interested in taking part in this project, nor anyone seem to have the basic skills to do so.

**Comment by bakinat** [comment]
Indeed I use the English UI, so you are probably right..
I originally mistakenly thought this project is about Hebrew support in
general and not just the UI..
Thanks, Barak

**Comment by ingbrzy** [comment]
Hebrew will be disabled in next update...
